### ISSUE TITLE
glBars black window background question?

### ISSUE THREAD

**Issue by mikobuntu** [DISTRHO/glBars#1]
Hi @falkTX . 

Is it possible that the actual glBars ( visual spectrum part ) can run without the need for the actual window?
Right now i can use devilspie to get rid of the window decoration, but would ideally like to just have the spinning bars without the black background.
'Im thinking that if it does indeed need the window, for co-ordinates and such, then would it be possible to set this as fully transparent ? 
[ mockup ]
![bit1](https://cloud.githubusercontent.com/assets/335217/21598780/6168c976-d15a-11e6-9fb0-516782f5fbf8.png)

thanks :)

**Comment by falkTX** [comment]
glBars is a plugin, so it is not the one that creates the window.

if you feel like hacking some code, try it out on the jack standalone version:
https://github.com/nedko/jack_glbars

**Comment by mikobuntu** [comment]
@falkTX thank you :)

**Comment by falkTX** [comment]
Closing this request as won't do. Not possible in the context of a plugin.
