### ISSUE TITLE
getGeometryConstraints error

### ISSUE THREAD

**Issue by RyLeeHarrison** [DISTRHO/glBars#2]
(base) ➜  glBars-master make all          
/Library/Developer/CommandLineTools/usr/bin/make -C dpf/dgl opengl FILE_BROWSER_DISABLED=true
Compiling src/Application.cpp
Compiling src/ApplicationPrivateData.cpp
Compiling src/Color.cpp
Compiling src/EventHandlers.cpp
Compiling src/Geometry.cpp
Compiling src/ImageBase.cpp
Compiling src/ImageBaseWidgets.cpp
Compiling src/Resources.cpp
Compiling src/SubWidget.cpp
Compiling src/SubWidgetPrivateData.cpp
Compiling src/TopLevelWidget.cpp
Compiling src/TopLevelWidgetPrivateData.cpp
Compiling src/Widget.cpp
Compiling src/WidgetPrivateData.cpp
Compiling src/Window.cpp
Compiling src/WindowPrivateData.cpp
Compiling src/OpenGL.cpp (OpenGL variant)
Compiling src/NanoVG.cpp (OpenGL variant)
Compiling src/pugl.mm (OpenGL variant)
Creating libdgl-opengl.a
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: ../build/libdgl-opengl.a(ImageBaseWidgets.cpp.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/make all -C plugins/glBars
Compiling DistrhoPluginGLBars.cpp
Compiling DistrhoUIGLBars.cpp
In file included from DistrhoUIGLBars.cpp:22:
In file included from ./DistrhoUIGLBars.hpp:27:
./ResizeHandle.hpp:125:46: error: no member named 'getGeometryConstraints' in 'DGL::Window'
        const Size<uint> minSize(getWindow().getGeometryConstraints(keepAspectRatio));
                                 ~~~~~~~~~~~ ^
./ResizeHandle.hpp:166:38: error: use of undeclared identifier 'kMouseCursorDiagonal'
        setCursor(shouldHaveCursor ? kMouseCursorDiagonal : kMouseCursorArrow);
                                     ^
./ResizeHandle.hpp:166:61: error: use of undeclared identifier 'kMouseCursorArrow'
        setCursor(shouldHaveCursor ? kMouseCursorDiagonal : kMouseCursorArrow);
                                                            ^
3 errors generated.
make[1]: *** [../../build/glBars/DistrhoUIGLBars.cpp.o] Error 1
make: *** [plugins] Error 2

**Comment by RyLeeHarrison** [comment]
ResizeHandle.hpp, line 125

**Comment by falkTX** [comment]
Use the develop branch of DPF

**Comment by falkTX** [comment]
Just an FYI, the git submodule is supposed to point to a specific commit of DPF, not to master or develop.
And if this is for packaging, consider using https://github.com/DISTRHO/DPF-Plugins/ instead
